name: "Fedora: Build and push toolbx images"

permissions: read-all

on:
  pull_request:
    branches:
      - main
    paths:
      - fedora/**
      - .github/workflows/fedora.yaml
  push:
    branches:
      - main
    paths:
      - fedora/**
      - .github/workflows/fedora.yaml
  schedule:
    - cron:  '0 0 * * MON'

env:
  distro: 'fedora'
  latest_release: '42'
  #platforms: 'linux/amd64, linux/arm64'
  platforms: 'linux/amd64'

# Prevent multiple workflow runs from racing to ensure that pushes are made
# sequentially for the main branch. Also cancel in progress workflow runs for
# pull requests only.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-push-images:
    strategy:
      fail-fast: false
      matrix:
        release: ['41', '42']

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      #- name: Set up QEMU for multi-arch builds
      #  shell: bash
      #  run: |
      #    sudo apt update
      #    sudo apt install qemu-user-static

      - name: Build container image
        uses: redhat-actions/buildah-build@v2
        if: env.latest_release != matrix.release
        with:
          platforms: ${{ env.platforms }}
          context: ${{ env.distro }}/${{ matrix.release }}
          image: ${{ env.distro }}-toolbox
          tags: ${{ matrix.release }}
          containerfiles: ${{ env.distro }}/${{ matrix.release }}/Containerfile
          layers: false
          oci: true

      - name: Build container image (latest tag)
        uses: redhat-actions/buildah-build@v2
        if: env.latest_release == matrix.release
        with:
          platforms: ${{ env.platforms }}
          context: ${{ env.distro }}/${{ matrix.release }}
          image: ${{ env.distro }}-toolbox
          tags: ${{ matrix.release }} latest
          containerfiles: ${{ env.distro }}/${{ matrix.release }}/Containerfile
          layers: false
          oci: true
          
      - name: Log in to the GitHub Container registry
        uses: redhat-actions/podman-login@v1
        if: (github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/main'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to Container Registry
        uses: redhat-actions/push-to-registry@v2
        id: push
        if: (github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/main' && env.latest_release != matrix.release
        with:
          image: ${{ env.distro }}-toolbox
          registry: ghcr.io/${{ github.actor }}/toolboxes
          tags: ${{ matrix.release }}

      - name: Push to Container Registry (latest tag)
        uses: redhat-actions/push-to-registry@v2
        id: push-latest
        if: (github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/main' && env.latest_release == matrix.release
        with:
          image: ${{ env.distro }}-toolbox
          registry: ghcr.io/${{ github.actor }}/toolboxes
          tags: ${{ matrix.release }} latest

      - uses: sigstore/cosign-installer@v3.3.0
        if: (github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/main'

      - name: Sign container image
        if: (github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/main' && env.latest_release != matrix.release
        run: |
          cosign sign -y --recursive --key env://COSIGN_PRIVATE_KEY ghcr.io/${{ github.actor }}/toolboxes/${{ env.distro }}-toolbox@${{ steps.push.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

      - name: Sign container image (latest)
        if: (github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/main' && env.latest_release == matrix.release
        run: |
          cosign sign -y --recursive --key env://COSIGN_PRIVATE_KEY ghcr.io/${{ github.actor }}/toolboxes/${{ env.distro }}-toolbox@${{ steps.push-latest.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
